export const ADD_TO_CART_ITEM = "ADD_TO_CART_ITEM";
export const REMOVE_TO_CART_ITEM = "REMOVE_TO_CART_ITEM";
export const SHIPPING_ADDRESS_TO_CART = "SHIPPING_ADDRESS_TO_CART";
export const PAYMENT_METHOD_TO_CART = "PAYMENT_METHOD_TO_CART";
